version: '3'

services:
  db:
    container_name: api_tasksync
    image: ${MYSQL_IMAGE}
    restart: always
    ports:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - C:\Users\gabri\banco:/backup
    networks:
      - api_tasksync_net

networks:
  api_tasksync_net:
    driver: bridge
